### ISSUE TITLE
Firmware build instructions

### ISSUE THREAD

**Issue by parsley72** [Vulcainreo/DVID#11]
How do I build the firmware?

**Comment by Vulcainreo** [comment]
Hello,
I have published a docker image to build firmware : https://hub.docker.com/r/vulcainreo/dvid-ino

Be sure that your firmware in under /src/ and name sketch.ino. 

The docker can be run at the top dir with this command : 
```bash
docker run -v (pwd)/src:/build/src -v (pwd)/build:/build/build  vulcainreo/dvid-ino
```

**Comment by parsley72** [comment]
https://github.com/Vulcainreo/DVID/pull/13
