### ISSUE TITLE
Hardcoded password training (doc)

### ISSUE THREAD

**Issue by cryptax** [Vulcainreo/DVID#2]
It isn't very clear how to setup the DVID board for this challenge.
Note: _This is rather a doc enhancement request / or doc issue than a bug._

I guessed the following, but am not entirely sure.

1. The "trainer" uploads the firmware using USBasp e.g. `sudo ./avrdude -c usbasp -p m328p -C ./avrdude.conf -U flash:w:./hardcodedPassword.ino.with_bootloader.standard.hex`. Then he hands over the board to a trainee / student.

2. The "student" connects the USB TTL to the board, writes to the serial connection, supplying various password attempts. S/he downloads the firmware, reverses it and supplies the correct hardcoded password.

Is this correct?

**Comment by Vulcainreo** [comment]
Hello,
Thanks for feedback.

Yes, about the setup, it's correct.
I added instruction file in each training to describe goal and guideline to achieve the training.
Arnaud.
