### ISSUE TITLE
Board generates garbage input 

### ISSUE THREAD

**Issue by cryptax** [Vulcainreo/DVID#3]
I get this issue frequently, but not always, on several different trainings. The board receives **garbage input**, and consequently *does not validate the input.* 

**Example #1 . BLE characteristics training**
I boot/power the board. It prints the message asking to send `abcd`. I haven't sent anything yet, haven't even connected to the board that it has already apparently received garbage data (e.g `AME=D\nVID-TAA` -- an overflow somewhere?) and prints this as the incoming pass. When I send `abcd`, it does not validate it, because it apparently receives something else. Note that I have validated the challenge in other cases.
Note this example does not use UART.

**Example #2. Default password**
I boot/power the board. It asks for a password. I send it via UART 9600 bauds. It says the password is incorrect (actually, it is correct, but nevermind at this step, the issue is rather that it does not receive it correctly) but does not print correctly what I have sent. Random ASCII chars garbage instead.
In case the USB to TTL is faulty, I have tested with another one. Same problem.

I have been told such issues could be related to bad ground or VCC connections on the board, but to be honest, I have no idea what's happening.

**Comment by Vulcainreo** [comment]
Hello,
Thank you for feedback. Have you tried to power the DVID from uart only ? Also, are you connect the power first and RX / TX next ?
This issue is already known (rare condition) and a fix is on the way.

**Comment by cryptax** [comment]
>Have you tried to power the DVID from uart only ? 

Yes, several times. Same issue.

> Are you connect the power first and RX / TX next ?

Tried this. But no change.

**Comment by Vulcainreo** [comment]
Hello,
No possibility to reproduce the bug in lab. Please, re-open if needed.
