### ISSUE TITLE
documentation minor changes are required for dvid writeup 01 instructions

### ISSUE THREAD

**Issue by thomasgarai** [Vulcainreo/DVID#7]
For linux users reading these instructions ( https://podalirius.net/en/writeups/dvid-writeup-01-hardware-find-the-datasheet/ ) some additional info should be provided as follows:

Step 1: Assemble and connect DVID device to USB port.

Step 2: Find the bus and device id using the following command:
**lsusb**

Step 3: Look for this line in the output of lsusb command to get device and bus id:
**_Bus 002 Device 012: ID 16c0:05dc Van Ooijen Technische Informatica shared ID for use with libusb_**

Step 4: create access to this device using the following command:
**sudo chmod a+w /dev/bus/usb/002/012**

Step 5: flash the EEPROM using the following command:
**avrdude -F -v -patmega328p -P/dev/bus/usb/002/012 -cusbasp -u -U flash:w:findTheDatasheet.ino.arduino_standard.hex**

tail of sample output below:
=====================
Writing | ################################################## | 100% 7.30s

avrdude: 14346 bytes of flash written
avrdude: verifying flash memory against findTheDatasheet.ino.arduino_standard.hex:
avrdude: load data flash data from input file findTheDatasheet.ino.arduino_standard.hex:
avrdude: input file findTheDatasheet.ino.arduino_standard.hex auto detected as Intel Hex
avrdude: input file findTheDatasheet.ino.arduino_standard.hex contains 14346 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 3.72s

avrdude: verifying ...
avrdude: 14346 bytes of flash verified

avrdude done.  Thank you.

**Comment by Vulcainreo** [comment]
Hello,
Thank you for details. I plan to add those elements in Wiki of the project for troubleshooting.
I will close the issue.
